### ISSUE TITLE
Typography Fixes based on Twitter Feedback

### ISSUE THREAD

**Issue by Haacked** [Haacked/haacked.com#598]
- [ ] Title in sidebar can overflow at times ![](https://pbs.twimg.com/media/DvorZAkVAAA2L3-.jpg)
- [ ] Decrease font size for mobile ![image](https://user-images.githubusercontent.com/19977/50544262-91ca3100-0ba4-11e9-81cf-81fb09db06cc.png)

**Comment by SeanKilleen** [comment]
I think the font itself is really nice and super readable.

Along the lines of overflow, I noticed the below -- figured may be related or it's own thing:

![image](https://user-images.githubusercontent.com/2148318/50544280-386efb80-0bbe-11e9-91d9-8728524eadd4.png)

**Comment by Haacked** [comment]
@SeanKilleen I can't repro the overflow. What conditions lead to it? Browser, OS, etc?

**Comment by Haacked** [comment]
@SeanKilleen nevermind, I see it.

**Comment by SeanKilleen** [comment]
👍 Fixed now as far as I can see.

Only thing I see now is that the "d" is a little cut off:

![image](https://user-images.githubusercontent.com/2148318/50561428-b4f5fd00-0cd8-11e9-8635-c6c832e6a51b.png)

(I'm on Chrome latest stable with a Dell XPS 15 on Win 10 v1809 btw)

**Comment by Haacked** [comment]
Thanks @SeanKilleen! I'll have to try this on my son's computer when I get home. Looks fine on a Mac.

**Comment by Haacked** [comment]
I just pushed a change to the theme that should fix this: https://github.com/Haacked/haackbar/pull/14

I had to push a much needed change to my About page to trigger a rebuild. It should be done in a few seconds.

**Comment by Haacked** [comment]
So I think this is fixed now. @SeanKilleen how does it look to you?

**Comment by SeanKilleen** [comment]
@Haacked I killed my cache but I'm still seeing it: 

> ![image](https://user-images.githubusercontent.com/2148318/50830896-2f490180-1317-11e9-9472-affc1491d17a.png)

It definitely looks better -- I can tell it's a `d`, but still bleeds past the sidebar.

**Comment by Haacked** [comment]
@SeanKilleen could you take one more look. I decided to use a Google web font so that it's the same font on both Mac and Windows.

**Comment by SeanKilleen** [comment]
Looks to still be the case. Cleared the case.

> ![image](https://user-images.githubusercontent.com/2148318/52734258-b7fc3280-2f92-11e9-9e06-0dceefc734d6.png)

Here's the computed style options in case that helps:

> ![image](https://user-images.githubusercontent.com/2148318/52734309-d8c48800-2f92-11e9-91be-554a5449185b.png)

If I drop the font size from 63px in Chrome to 56 or 57, it appears to fix it.

**Comment by Haacked** [comment]
Ok, I finally fixed it. Turns out it was a dumb mistake. I had the URL format for the Open Sans Condensed URL incorrect so it wasn't actually rendering that font. https://github.com/Haacked/haackbar/pull/15

**Comment by SeanKilleen** [comment]
Looks great!

> ![image](https://user-images.githubusercontent.com/2148318/53129910-d506a780-3536-11e9-83b3-8d1814656271.png)
